//created on: Aug 2, 2018
package testRule

//list any import classes here.
import com.lol.model.champions.ChampionListDto;
import com.lol.Test;
import java.lang.System;
import com.lol.model.champions.ChampionsAndRoles;
import com.lol.model.champions.Champion;
import com.lol.model.champions.Stats;
import com.lol.model.ChampionRolesEnum;
import com.lol.model.PlayerPositions;
import java.util.List;
import java.util.ArrayList;

//declare any global variables here

rule "MAGES are mostly MID"
	when
		$champ: ChampionsAndRoles(mainRole contains ChampionRolesEnum.MAGE)
	then
		PlayerPositions position = PlayerPositions.MID;
		List<PlayerPositions> positions = $champ.getPlayedPositions();
		
		if(positions == null) {
			positions = new ArrayList<PlayerPositions>();
		}
		
		positions.add(position);
		
		$champ.setPlayedPositions(positions);
end

rule "MARKSMEN are mostly BOTTOM"
	when
		$champ: ChampionsAndRoles(mainRole contains ChampionRolesEnum.MARKSMAN)
	then
		PlayerPositions position = PlayerPositions.BOTTOM;
		List<PlayerPositions> positions = $champ.getPlayedPositions();
		
		if(positions == null) {
			positions = new ArrayList<PlayerPositions>();
		}
		
		positions.add(position);
		
		$champ.setPlayedPositions(positions);
end

rule "CONTROLLERS are mostly SUPPORT"
	when
		$champ: ChampionsAndRoles(mainRole contains ChampionRolesEnum.CONTROLLER)
	then
		PlayerPositions position = PlayerPositions.SUPPORT;
		List<PlayerPositions> positions = $champ.getPlayedPositions();
		
		if(positions == null) {
			positions = new ArrayList<PlayerPositions>();
		}
		
		positions.add(position);
		
		$champ.setPlayedPositions(positions);
end

rule "WARDEN TANKS are mostly SUPPORT"
	when
		$champ: ChampionsAndRoles(mainRole contains ChampionRolesEnum.TANK && subroles contains ChampionRolesEnum.WARDEN)
	then
		PlayerPositions position = PlayerPositions.SUPPORT;
		List<PlayerPositions> positions = $champ.getPlayedPositions();
		
		if(positions == null) {
			positions = new ArrayList<PlayerPositions>();
		}
		
		positions.add(position);
		
		$champ.setPlayedPositions(positions);
end

rule "JUGGERNAUT FIGHTERS are mostly TOP"
	when
		$champ: ChampionsAndRoles(mainRole contains ChampionRolesEnum.FIGHTER && subroles contains ChampionRolesEnum.JUGGERNAUT)
	then
		PlayerPositions position = PlayerPositions.TOP;
		List<PlayerPositions> positions = $champ.getPlayedPositions();
		
		if(positions == null) {
			positions = new ArrayList<PlayerPositions>();
		}
		
		positions.add(position);
		
		$champ.setPlayedPositions(positions);
end

rule "DIVER FIGHTERS are JUNGLE and TOP"
	when
		$champ: ChampionsAndRoles(mainRole contains ChampionRolesEnum.FIGHTER && subroles contains ChampionRolesEnum.DIVER)
	then
		PlayerPositions position1 = PlayerPositions.JUNGLE;
		PlayerPositions position2 = PlayerPositions.TOP;
		List<PlayerPositions> positions = $champ.getPlayedPositions();
		
		if(positions == null) {
			positions = new ArrayList<PlayerPositions>();
		}
		
		positions.add(position1);
		positions.add(position2);
		
		$champ.setPlayedPositions(positions);
end

rule "SKRIMISHER SLAYERS can be played TOP"
	when
		$champ: ChampionsAndRoles(mainRole contains ChampionRolesEnum.SLAYER && subroles contains ChampionRolesEnum.SKRIMISHER)
	then
		PlayerPositions position = PlayerPositions.TOP;
		List<PlayerPositions> positions = $champ.getPlayedPositions();
		
		if(positions == null) {
			positions = new ArrayList<PlayerPositions>();
		}
		
		positions.add(position);
		
		$champ.setPlayedPositions(positions);
end

rule "ASSASSIN SLAYERS can be played MID"
	when
		$champ: ChampionsAndRoles(mainRole contains ChampionRolesEnum.SLAYER && subroles contains ChampionRolesEnum.ASSASSIN)
	then
		PlayerPositions position = PlayerPositions.MID;
		List<PlayerPositions> positions = $champ.getPlayedPositions();
		
		if(positions == null) {
			positions = new ArrayList<PlayerPositions>();
		}
		
		positions.add(position);
		
		$champ.setPlayedPositions(positions);
end

rule "ARTILLERY MAGES can be played SUPPORT"
	when
		$champ: ChampionsAndRoles(mainRole contains ChampionRolesEnum.MAGE && subroles contains ChampionRolesEnum.ARTILLERY)
	then
		PlayerPositions position = PlayerPositions.SUPPORT;
		List<PlayerPositions> positions = $champ.getPlayedPositions();
		
		if(positions == null) {
			positions = new ArrayList<PlayerPositions>();
		}
		
		positions.add(position);
		
		$champ.setPlayedPositions(positions);
end

rule "Battlemages with Hp Regen >= 6.6 can be played TOP"
	when
		$stats: Stats(hpregen >= 6.6)
		$champion: Champion(stats == $stats)
		$champ: ChampionsAndRoles(mainRole contains ChampionRolesEnum.MAGE
									 && subroles contains ChampionRolesEnum.BATTLEMAGE
									 && champion == $champion)
	then
		PlayerPositions position = PlayerPositions.TOP;
		List<PlayerPositions> positions = $champ.getPlayedPositions();
		
		if(positions == null) {
			positions = new ArrayList<PlayerPositions>();
		}
		
		positions.add(position);
		
		$champ.setPlayedPositions(positions);
end

rule "SPECIALISTS can be played TOP and MID"
	when
	$champ: ChampionsAndRoles(mainRole contains ChampionRolesEnum.SPECIALIST)
	then
		PlayerPositions position1 = PlayerPositions.TOP;
		PlayerPositions position2 = PlayerPositions.MID;
		List<PlayerPositions> positions = $champ.getPlayedPositions();
		
		if(positions == null) {
			positions = new ArrayList<PlayerPositions>();
		}
		
		positions.add(position1);
		positions.add(position2);
		
		$champ.setPlayedPositions(positions);
end

rule "SPECIALISTS range > 400 and AD > 55 can be played BOTTOM AND JUNGLE"
	when
		$stats: Stats(attackrange > 400 && attackdamage >= 55)
		$champion: Champion(stats == $stats)
		$champ: ChampionsAndRoles(mainRole contains ChampionRolesEnum.SPECIALIST && champion == $champion)
	then
		PlayerPositions position1 = PlayerPositions.BOTTOM;
		PlayerPositions position2 = PlayerPositions.JUNGLE;
		List<PlayerPositions> positions = $champ.getPlayedPositions();
		
		if(positions == null) {
			positions = new ArrayList<PlayerPositions>();
		}
		
		positions.add(position1);
		positions.add(position2);
		
		$champ.setPlayedPositions(positions);
end

rule "SPECIALISTS range > 400 and AD < 52 and armor > 20 are SUPPORTS"
	when
		$stats: Stats(attackrange > 400 && attackdamage < 52 && armor > 20)
		$champion: Champion(stats == $stats)
		$champ: ChampionsAndRoles(mainRole contains ChampionRolesEnum.SPECIALIST && champion == $champion)
	then
		PlayerPositions position = PlayerPositions.SUPPORT;
		List<PlayerPositions> positions = $champ.getPlayedPositions();
		
		if(positions == null) {
			positions = new ArrayList<PlayerPositions>();
		}
		
		positions.add(position);
		
		$champ.setPlayedPositions(positions);
end

rule "VANGUARD TANKS AD > 59.8 and armor+mr > 67 are SUPPORTS"
	when
		$stats: Stats(attackdamage > 59.8 && armor + spellblock > 67)
		$champion: Champion(stats == $stats)
		$champ: ChampionsAndRoles(mainRole contains ChampionRolesEnum.TANK &&
								  subroles contains ChampionRolesEnum.VANGUARD && 
								  champion == $champion)
	then
		PlayerPositions position = PlayerPositions.SUPPORT;
		List<PlayerPositions> positions = $champ.getPlayedPositions();
		
		if(positions == null) {
			positions = new ArrayList<PlayerPositions>();
		}
		
		positions.add(position);
		
		$champ.setPlayedPositions(positions);
end

rule "VANGUARD TANKS AD >= 62 are TOP"
	when
		$stats: Stats(attackdamage >= 62)
		$champion: Champion(stats == $stats)
		$champ: ChampionsAndRoles(mainRole contains ChampionRolesEnum.TANK &&
								  subroles contains ChampionRolesEnum.VANGUARD && 
								  champion == $champion)
	then
		PlayerPositions position = PlayerPositions.TOP;
		List<PlayerPositions> positions = $champ.getPlayedPositions();
		
		if(positions == null) {
			positions = new ArrayList<PlayerPositions>();
		}
		
		positions.add(position);
		
		$champ.setPlayedPositions(positions);
end

/*--------------------------------Champions that are hard to generalize--------------------------------*/

rule "VANGUARD TANKS that are JUNGLE"
	when
		$champ: ChampionsAndRoles(mainRole contains ChampionRolesEnum.TANK &&
								  subroles contains ChampionRolesEnum.VANGUARD && 
								  (name == "Zac" || name == "Gragas" || name == "Rammus" || name == "Sejuani" || name == "Amumu"))
	then
		PlayerPositions position = PlayerPositions.JUNGLE;
		List<PlayerPositions> positions = $champ.getPlayedPositions();
		
		if(positions == null) {
			positions = new ArrayList<PlayerPositions>();
		}
		
		positions.add(position);
		
		$champ.setPlayedPositions(positions);
end

rule "SLAYERS that are JUNGLE"
	when
		$champ: ChampionsAndRoles(mainRole contains ChampionRolesEnum.SLAYER &&
								  (name == "Evelynn" || name == "Kayn" || name == "Kha'Zix" 
								  || name == "Nocturne" || name == "Shaco" || name == "Jax" 
								  || name == "Master Yi" || name == "Tryndamere"))
	then
		PlayerPositions position = PlayerPositions.JUNGLE;
		List<PlayerPositions> positions = $champ.getPlayedPositions();
		
		if(positions == null) {
			positions = new ArrayList<PlayerPositions>();
		}
		
		positions.add(position);
		
		$champ.setPlayedPositions(positions);
end

rule "SKRIMISHER SLAYERS that are MID"
	when
		$champ: ChampionsAndRoles(mainRole contains ChampionRolesEnum.SLAYER &&
								  subroles contains ChampionRolesEnum.SKRIMISHER && 
								  (name == "Yasuo" || name == "Kayn" || name == "Kha'Zix" 
								  || name == "Nocturne" || name == "Shaco" || name == "Jax" 
								  || name == "Master Yi" || name == "Tryndamere"))
	then
		PlayerPositions position = PlayerPositions.MID;
		List<PlayerPositions> positions = $champ.getPlayedPositions();
		
		if(positions == null) {
			positions = new ArrayList<PlayerPositions>();
		}
		
		positions.add(position);
		
		$champ.setPlayedPositions(positions);
end