//created on: Aug 2, 2018
package testRule

//list any import classes here.
import com.lol.model.champions.ChampionListDto;

//declare any global variables here




rule "Your First Rule"

    when
       $cl: ChampionListDto(version == null)
    then
        System.out.println("Hello!");

end

rule "Your Second Rule"
    //include attributes such as "salience" here...
    when
        //conditions
    then
        //actions

end
