//created on: Aug 2, 2018
package testRule

//list any import classes here.
import com.lol.model.champions.ChampionListDto;
import com.lol.Test;
//declare any global variables here


rule "Your First Rule"

    when
       $cl: ChampionListDto(version == null)
    then
    	$cl.setVersion("ASDF");
        System.out.println("Hello!");

end

rule "Your Second Rule"
    //include attributes such as "salience" here...
    when
        $test: Test(test == 1)
    then
        $test.setTest(3);
        System.out.println("Hello from rules!");

end
